// fixtures/mini-ds/react/dropdown-menu.tsx
import { createContext, useContext, useEffect, useId, useRef, useState } from "react";
import type { ReactNode } from "react";

const DropdownMenuContext = createContext<{ close: () => void } | null>(null);

function enabledItems(menu: HTMLElement | null) {
  return Array.from(menu?.querySelectorAll<HTMLElement>('[role="menuitem"]') ?? []).filter(
    (item) => item.getAttribute("aria-disabled") !== "true",
  );
}

export interface DropdownMenuProps {
  label: string;
  children: ReactNode;
}

export function DropdownMenu({ label, children }: DropdownMenuProps) {
  const [open, setOpen] = useState(false);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const menuRef = useRef<HTMLDivElement>(null);
  const menuId = useId();

  function close() {
    setOpen(false);
    triggerRef.current?.focus();
  }

  useEffect(() => {
    if (!open) return;

    enabledItems(menuRef.current)[0]?.focus();

    function handleKeyDown(event: KeyboardEvent) {
      const items = enabledItems(menuRef.current);
      if (items.length === 0) return;
      const currentIndex = items.indexOf(document.activeElement as HTMLElement);

      if (event.key === "ArrowDown") {
        event.preventDefault();
        items[(currentIndex + 1) % items.length].focus();
      } else if (event.key === "ArrowUp") {
        event.preventDefault();
        items[(currentIndex - 1 + items.length) % items.length].focus();
      } else if (event.key === "Escape") {
        event.preventDefault();
        close();
      }
    }

    function handlePointerDown(event: PointerEvent) {
      const target = event.target as Node;
      const inMenu = menuRef.current?.contains(target) ?? false;
      const inTrigger = triggerRef.current?.contains(target) ?? false;
      if (!inMenu && !inTrigger) setOpen(false);
    }

    document.addEventListener("keydown", handleKeyDown);
    document.addEventListener("pointerdown", handlePointerDown);
    return () => {
      document.removeEventListener("keydown", handleKeyDown);
      document.removeEventListener("pointerdown", handlePointerDown);
    };
  }, [open]);

  return (
    <div>
      <button
        type="button"
        ref={triggerRef}
        aria-haspopup="menu"
        aria-expanded={open}
        onClick={() => setOpen((value) => !value)}
      >
        {label}
      </button>
      <div ref={menuRef} id={menuId} role="menu" hidden={!open}>
        <DropdownMenuContext.Provider value={{ close }}>{children}</DropdownMenuContext.Provider>
      </div>
    </div>
  );
}

export interface MenuItemProps {
  onSelect?: () => void;
  disabled?: boolean;
  children: ReactNode;
}

export function MenuItem({ onSelect, disabled = false, children }: MenuItemProps) {
  const context = useContext(DropdownMenuContext);

  return (
    <button
      type="button"
      role="menuitem"
      aria-disabled={disabled || undefined}
      onClick={() => {
        if (disabled) return;
        onSelect?.();
        context?.close();
      }}
    >
      {children}
    </button>
  );
}

export interface MenuLinkProps {
  href: string;
  children: ReactNode;
}

export function MenuLink({ href, children }: MenuLinkProps) {
  const context = useContext(DropdownMenuContext);

  return (
    <a role="menuitem" href={href} onClick={() => context?.close()}>
      {children}
    </a>
  );
}

// fixtures/mini-ds/web-components/dropdown-menu.ts
const TAG = "ds-dropdown-menu";

class DsDropdownMenu extends HTMLElement {
  #trigger: HTMLButtonElement | null = null;
  #menu: HTMLElement | null = null;

  connectedCallback() {
    const trigger = this.querySelector('[data-slot="trigger"]');
    const menu = this.querySelector('[role="menu"]');
    if (!(trigger instanceof HTMLButtonElement) || !(menu instanceof HTMLElement)) return;

    this.#trigger = trigger;
    this.#menu = menu;

    trigger.setAttribute("aria-haspopup", "menu");
    trigger.setAttribute("aria-expanded", "false");
    menu.hidden = true;

    trigger.addEventListener("click", this.#handleTriggerClick);
    menu.addEventListener("keydown", this.#handleMenuKeydown);
    menu.addEventListener("click", this.#handleMenuClick);
    document.addEventListener("pointerdown", this.#handleOutsidePointer);
  }

  disconnectedCallback() {
    document.removeEventListener("pointerdown", this.#handleOutsidePointer);
  }

  #items(): HTMLElement[] {
    if (!this.#menu) return [];
    return Array.from(this.#menu.querySelectorAll('[role="menuitem"]')).filter(
      (el): el is HTMLElement =>
        el instanceof HTMLElement && el.getAttribute("aria-disabled") !== "true",
    );
  }

  #open() {
    if (!this.#trigger || !this.#menu) return;
    this.#menu.hidden = false;
    this.#trigger.setAttribute("aria-expanded", "true");
    this.#items()[0]?.focus();
  }

  #close(returnFocus: boolean) {
    if (!this.#trigger || !this.#menu) return;
    this.#menu.hidden = true;
    this.#trigger.setAttribute("aria-expanded", "false");
    if (returnFocus) this.#trigger.focus();
  }

  #handleTriggerClick = () => {
    if (!this.#menu) return;
    if (this.#menu.hidden) this.#open();
    else this.#close(false);
  };

  #handleMenuKeydown = (event: KeyboardEvent) => {
    const items = this.#items();
    if (items.length === 0) return;
    const currentIndex = items.indexOf(document.activeElement as HTMLElement);

    if (event.key === "ArrowDown") {
      event.preventDefault();
      const next = currentIndex === -1 ? 0 : (currentIndex + 1) % items.length;
      items[next]?.focus();
    } else if (event.key === "ArrowUp") {
      event.preventDefault();
      const prev =
        currentIndex === -1 ? items.length - 1 : (currentIndex - 1 + items.length) % items.length;
      items[prev]?.focus();
    } else if (event.key === "Escape") {
      event.preventDefault();
      this.#close(true);
    }
  };

  #handleMenuClick = (event: MouseEvent) => {
    const target = event.target instanceof Element ? event.target.closest('[role="menuitem"]') : null;
    if (!target || target.getAttribute("aria-disabled") === "true") return;
    this.#close(false);
  };

  #handleOutsidePointer = (event: PointerEvent) => {
    if (!this.#menu || this.#menu.hidden) return;
    if (event.target instanceof Node && this.contains(event.target)) return;
    this.#close(false);
  };
}

if (!customElements.get(TAG)) {
  customElements.define(TAG, DsDropdownMenu);
}

export {};
